### PR TITLE
switch to dune, fix immutable-string -> bytes

### PR DESCRIPTION
**Pull request by zapashcanon**
Hi,

I switched to dune and fixed some type errors related to `String`/`Bytes`.

Cheers.

### CODE REVIEW

**Comment by briancaine** [comment]
Cool, thanks!

**Comment by zapashcanon** [comment]
@briancaine thanks for merging. Do you think you could do a new release on opam ?

**Comment by briancaine** [comment]
I started on a new release, but apparently I'm tripping up some of the automated tests: https://github.com/ocaml/opam-repository/pull/14793

I'll need to find the time to work on resolving the issues.

**Comment by zapashcanon** [comment]
It simply looks like `Bytes.of_string` is not available in `4.03` you can just edit the opam file to require at least `4.04`.

**Pull request merged**
